### ISSUE TITLE
Wrong symmetry operation for Hexagonal Low

### ISSUE THREAD

**Issue by lekah** [BlueQuartzSoftware/EbsdLib#17]
There seems to be an issue with the hexagonal symmetry operations.
The fourth symop should have 0.5 as its 0,0 element, the line in the source code being:
https://github.com/BlueQuartzSoftware/EbsdLib/blob/dc41bff604f56fb309368a3fb99b65b12a362494/Source/EbsdLib/LaueOps/HexagonalLowOps.cpp#L85
I compared with slide 50 here: http://pajarito.materials.cmu.edu/lectures/L3-OD_symmetry-21Jan16.pdf

**Comment by imikejackson** [comment]
Fixed with push https://github.com/BlueQuartzSoftware/EbsdLib/commit/c2de608890038fef185c9f479e1455ad7e5ff874
