### ISSUE TITLE
Order of symmetry operations in calculation of misorientation angle

### ISSUE THREAD

**Issue by lekah** [BlueQuartzSoftware/EbsdLib#19]
We noticed some discrepancies in the calculation of misorientation angles (happy to provide more information).
In a given example for cubic symmetry, two grains with Euler angles:
* 5.8827929,	1.0387267,	0.87234616
* 5.6574483,	0.1877138,	4.6545763

are given with a misorientation angle of 0.06 degrees (instead of 54.76 degrees which is what we calculated by applying the cubic symops).
We noticed in the sourcecode that the order of quaternion multiplication seems to be wrong in https://github.com/BlueQuartzSoftware/EbsdLib/blob/05609fcc2d05b779c586630df26d7e26f8d85ad2/Source/EbsdLib/LaueOps/LaueOps.cpp#L101
the order of multiplication is  O * q1 * q2.T instead of q1 * O * q2.T which is not the same as the rotations don't commute if I understood well.
If this part of the code is used to calculate misorientation angles this might explain the discrepancy.

**Comment by imikejackson** [comment]
@lekah I tried to reproduce the results, but this is what I have:

```
  CubicOps ops;
{
  QuatD q1(0, 0, -0.25881905, 0.96592583); // 30,0,0 Euler
  QuatD q2(0, 0, -0.38268343, 0.92387953); // 45,0,0 Euler

  Orientation<double> misor = ops.calculateMisorientation(q1, q2);
  std::cout << misor[0] << ", " << misor[1] << ", " << misor[2] << "\n";
  std::cout << "Misorientation Angle: " << misor[3] * 180.0/3.1415927 << "\n";
}

{
  // Euler1 5.8827929, 1.0387267, 0.87234616
  // Euler2 5.6574483, 0.1877138, 4.6545763
  QuatD q1(-0.39917575, 0.2949572, -0.20296388, 0.8440762000000001); // 30,0,0 Euler
  QuatD q2(-0.082181695, -0.045049419, 0.89922712, 0.42732575); // 45,0,0 Euler

  Orientation<double> misor = ops.calculateMisorientation(q1, q2);
  std::cout << misor[0] << ", " << misor[1] << ", " << misor[2] << "\n";
  std::cout << "Misorientation Angle: " << misor[3] * 180.0/3.1415927 << "\n";
}

```
and that gets me an output of:
```
0, 0, 1
Misorientation Angle: 15
0.429881, 0.460016, 0.776909
Misorientation Angle: 54.7613
```

It looks like at least the latest v1.0.28 version is correctly calculating the misorientation angle.

**Comment by lekah** [comment]
Ok, guess this issue can be closed then. It was probably fixed in the meanwhile...
